# Generated by Django 2.2.2 on 2019-06-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('headcount', models.IntegerField(default=1)),
                ('pgtype', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('img', models.ImageField(default='property-img-default.gif', upload_to='')),
                ('rent', models.IntegerField()),
                ('deposit', models.IntegerField()),
            ],
        ),
    ]
