# Generated by Django 2.2.2 on 2019-06-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
